# Generated by Django 5.2 on 2025-05-22 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.TextField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='product',
            name='carbs',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='product',
            name='fats',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='kilocalories',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='kilojoule',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_country',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='product',
            name='material_type',
            field=models.TextField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='product',
            name='packing_type',
            field=models.TextField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='product',
            name='proteins',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='product',
            name='recommendations',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.TextField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='specificity',
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_conditions',
            field=models.TextField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
