# Generated by Django 5.2 on 2025-06-10 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productcategory_options_product_brand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.TextField(blank=True, max_length=24, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbs',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, max_length=512, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=64, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_media', verbose_name='Фото продукции'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kilocalories',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='Ккал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kilojoule',
            field=models.PositiveIntegerField(default=0, verbose_name='КДж'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=24, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer_country',
            field=models.CharField(blank=True, max_length=24, verbose_name='Страна производитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material_type',
            field=models.TextField(blank=True, max_length=24, verbose_name='Тип материала'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='product',
            name='packing_type',
            field=models.TextField(blank=True, max_length=24, verbose_name='Тип упаковки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Белки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recommendations',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Рекомендации'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, max_length=64, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.TextField(blank=True, max_length=16, verbose_name='Размеры ШхВхГ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specificity',
            field=models.TextField(blank=True, max_length=512, verbose_name='Спецификация'),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage_conditions',
            field=models.TextField(blank=True, max_length=64, verbose_name='Условия хранения'),
        ),
        migrations.AlterUniqueTogether(
            name='basket',
            unique_together={('user', 'product')},
        ),
    ]
