<<<<<<< HEAD
# Generated by Django 5.2 on 2025-05-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.TextField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='product',
            name='carbs',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='product',
            name='energy_value',
            field=models.TextField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='fats',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='kilocalories',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='kilojoule',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_country',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='product',
            name='material_type',
            field=models.TextField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='product',
            name='nutritional_value',
            field=models.TextField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='packing_type',
            field=models.TextField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='product',
            name='proteins',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='recommendations',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.TextField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='specificity',
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_conditions',
            field=models.TextField(blank=True, max_length=64),
        ),
    ]
=======
# Generated by Django 5.2 on 2025-05-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.TextField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='product',
            name='carbs',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='product',
            name='energy_value',
            field=models.TextField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='fats',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='kilocalories',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='kilojoule',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_country',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='product',
            name='material_type',
            field=models.TextField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='product',
            name='nutritional_value',
            field=models.TextField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='packing_type',
            field=models.TextField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='product',
            name='proteins',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='recommendations',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.TextField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='specificity',
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_conditions',
            field=models.TextField(blank=True, max_length=64),
        ),
    ]
>>>>>>> e6c71d72ebdcdede1b1a96e346c55af79a9acc3d
