# Generated by Django 5.2 on 2025-06-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_order_address_alter_order_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
