# Generated by Django 5.2 on 2025-06-13 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_orderitem_order_remove_orderitem_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Имя получателя')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон получателя')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('apartment_office', models.CharField(blank=True, max_length=10, verbose_name='Кв./офис')),
                ('intercom', models.CharField(blank=True, max_length=10, verbose_name='Домофон')),
                ('entrance', models.CharField(blank=True, max_length=10, verbose_name='Подъезд')),
                ('floor', models.CharField(blank=True, max_length=10, verbose_name='Этаж')),
                ('courier_comment', models.TextField(blank=True, verbose_name='Комментарий курьеру')),
                ('order_comment', models.TextField(blank=True, verbose_name='Комментарий к заказу')),
                ('delivery_time', models.CharField(blank=True, max_length=50, verbose_name='Время доставки')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая цена')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за доставку')),
                ('service_fee', models.DecimalField(decimal_places=2, default=39, max_digits=10, verbose_name='Сервисный сбор')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('card_number', models.CharField(blank=True, max_length=16, verbose_name='Номер карты клиента')),
                ('cardholder_name', models.CharField(blank=True, max_length=100, verbose_name='Имя и фамилия на карте')),
                ('cvv', models.CharField(blank=True, max_length=4, verbose_name='CVV карты')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за единицу')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Товар')),
            ],
        ),
    ]
