# Generated by Django 5.2 on 2025-06-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Банковская карта'), ('sbp', 'СБП')], max_length=10, verbose_name='Способ оплаты'),
        ),
    ]
