# Generated by Django 5.2 on 2025-06-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Карта'), ('sbp', 'СБП')], max_length=10, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID транзакции'),
        ),
    ]
