# Generated by Django 5.2 on 2025-06-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(choices=[('now', 'Сейчас 35-45 мин'), ('9-10', '9:00-10:00'), ('10-11', '10:00-11:00'), ('11-12', '11:00-12:00'), ('12-13', '12:00-13:00'), ('13-14', '13:00-14:00'), ('14-15', '14:00-15:00'), ('15-16', '15:00-16:00'), ('16-17', '16:00-17:00'), ('17-18', '17:00-18:00'), ('18-19', '18:00-19:00'), ('19-20', '19:00-20:00'), ('20-21', '20:00-21:00')], default='now', max_length=10, verbose_name='Время доставки'),
        ),
    ]
